language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 7.4
    - 8.0

before_script:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - composer test
